/**
 *
 * Vala doesn't allow partial classes or class extensions,
 * so I'm faking it. These concrete classes will be replaced
 * with the implementation generated by entitas-cli.
 *
 *
 */
namespace Entitas {
  public class World : WorldBase {
    public static string[] componentsEnum;
    public static int totalComponents;
    public static World instance; 
    public World(string[] components, int startCreationIndex=0) {
      base(components, startCreationIndex);
    }

  }
  
}
